public class CalculatorController 
{
      public integer firstNumber {get;set;}
      public integer secondNumber {get;set;}
      public integer Result {get;set;}
      public CalculatorController()
      {
      }
      public  void Add()
      {
        result = firstNumber + secondNumber;
      }
      public void SUB()
      {
        result = firstNumber - SecondNumber;
      }
      public void MUL()
      {
        result = firstNumber * SecondNumber;
      }
      public void Division()
      {
       result = firstNumber/ secondNumber;
      }
}